[package]
name = "ds-project"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ds-project"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
tokio-stream = "0.1.16"
